# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_statuspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
